name: Build and Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - name: windows-latest  
            target: x86_64-pc-windows-msvc
            ext: '.exe'
          - name: macos-latest
            target: x86_64-apple-darwin
            ext: ''
            arch: 'Intel'
          - name: macos-latest
            target: aarch64-apple-darwin
            ext: ''
            arch: 'Apple Silicon'

    runs-on: ${{ matrix.platform.name }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install Node dependencies
      run: npm install

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.platform.target }}

    - name: Rust cache
      uses: swatinem/rust-cache@v2
      with:
        workspaces: "./src-tauri -> target"

    - name: Build Tauri App
      run: npm run tauri build -- --target ${{ matrix.platform.target }}

    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.platform.name }}-${{ matrix.platform.target }}-executable
        path: src-tauri/target/${{ matrix.platform.target }}/release/dotclient${{ matrix.platform.ext }}

    - name: Upload bundle (if exists)
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{ matrix.platform.name }}-${{ matrix.platform.target }}-bundle
        path: src-tauri/target/${{ matrix.platform.target }}/release/bundle/

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    permissions:
      contents: write
      releases: write
    steps:
    - uses: actions/checkout@v4
    
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
    
    - name: List artifacts (debug)
      run: find artifacts -type f -name "*" | head -20
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        body: |
          自动构建版本 v${{ github.run_number }}
          
          包含以下平台的构建文件：
          - Windows x86_64
          - macOS Intel (x86_64)
          - macOS Apple Silicon (aarch64)
        files: |
          artifacts/**/*
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
